name: ternaku
description: Apps Eyescan detection for animal.
publish_to: 'Ternaku'

version: 1.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 4.0.6
  http: ^0.13.3
  convert: ^3.0.1
  mysql1: 0.19.0
  image_picker: 0.8.4+1
  flutter_animated_dialog: 2.0.1
  flutter_staggered_grid_view: 0.6.2
  flutter_spinkit: 5.2.0
  flutter_bloc: 8.1.3
  google_fonts: 2.1.1
  flutter_svg: 1.0.0
  google_nav_bar: 5.0.0
  intl: 0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"  
flutter:
  assets:
    - assets/
    - assets/kambing.png
    - assets/sapi.png
    - assets/wave.png
    - assets/logoputih.png
  uses-material-design: true

